version: '3'

tasks:
  create:
    vars:
      CREATED_DAY_DIRS:
        sh: "ls -d */ | cut -f1 -d'/'"
      NEW_DAY_DIR: '{{splitList "\n" .CREATED_DAY_DIRS | sortAlpha | reverse | rest | sortAlpha | last | add 1}}'
    cmds:
      - mkdir -p {{.NEW_DAY_DIR}}
      # - cp main.py.stub {{.NEW_DAY_DIR}}/main.py
      - sed 's/##day##/{{.NEW_DAY_DIR}}/g' main.py.stub > {{.NEW_DAY_DIR}}/main.py
      - touch {{.NEW_DAY_DIR}}/README.md
      - touch {{.NEW_DAY_DIR}}/requirements.txt
      - touch {{.NEW_DAY_DIR}}/input.txt
      - touch {{.NEW_DAY_DIR}}/example.txt

  env:
    cmds:
      - pyenv install

  init:
    cmds:
      - pyenv local
      - pip install -r {{.CURRENT_DIR}}/requirements.txt

  run:
    vars:
      CURRENT_DIR: '{{splitList " " .CLI_ARGS | first }}'
    cmds:
      - task: init
        vars:
          CURRENT_DIR:
            ref: ".CURRENT_DIR"
        silent: true
      - python -m {{.CURRENT_DIR}}.main



    # silent: true